apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/AhmetKutlu/PulumiAKS-NodeExpress.git
    targetRevision: main
    path: argo-cd-apps/mysql
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
