name: Docker Image CI

on:
  push:
    branches: [ "main", "staging", "dev" ]
    paths:
      - "application/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build ./application/ --file ./application/Dockerfile --tag ahmetkutlu/cwnodeexpress:${GITHUB_REF#refs/heads/}
      
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ahmetkutlu
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push the Docker image
      run: docker push ahmetkutlu/cwnodeexpress:${GITHUB_REF#refs/heads/}
